<?php
/**@var \Blog\Entity\Post $post */
$this->headTitle('Blog');
?>
<h1>Blog</h1>

<p>
    <a href="<?=$this->url('admin-blog/post', ['action'=>'add']); ?>">
        New Post
    </a>
</p>

<table class="table">
    <thead>
    <tr>
        <th>Title</th>
        <th>Action</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($posts as $post): ?>
        <tr>
            <td><?=$this->escapeHtml($post->getTitle())?></td>
            <td>
                <a href="<?=$this->url('admin-blog/post', ['action'=>'edit', 'id'=>$post->getId()]); ?>">
                    Edit
                </a>
                <a href="<?=$this->url('admin-blog/post', ['action'=>'delete', 'id'=>$post->getId()]); ?>" class="delete">
                    Delete
                </a>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<script type="text/javascript">
    $(document).ready(function () {
        $('.delete').click(function () {
            if(!confirm('Você tem certez?'))
                return false;
        });
    });
</script>